UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Controllers/HomeController.cs
using STACK.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace STACK.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            //return View();
            return View(db.Questions.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using STACK.Models;
using Microsoft.AspNet.Identity;
using STACK.ViewModels;

namespace STACK.Controllers
{
    public class QuestionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Questions
        public ActionResult Index()
        {
            return View(db.Questions.ToList());
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            var qa = new QuestionAnswerViewModel
            {
                Question = question,
                NewAnswer = new Answer()
            };
            qa.NewAnswer.QuestionId = qa.Question.Id;
            return View(qa);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        // POST: Questions/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {

                question.ApplicationUserId = User.Identity.GetUserId();
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = question.Id });
            }

            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Question question = db.Questions.Find(id);
                if (question == null)
                {
                    return HttpNotFound();
                }
                return View(question);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }           
        }

        // POST: Questions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                question.ApplicationUserId = User.Identity.GetUserId();
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {

            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Question question = db.Questions.Find(id);
                if (question == null)
                {
                    return HttpNotFound();
                }
                return View(question);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }            
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        //GET : Questions/Answer/5
        public ActionResult Answer(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                Answer answer = new Answer();
                answer.QuestionId = id;
                return View(answer);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Answer(Answer answer)
        {
            if (ModelState.IsValid)
            {
                answer.ApplicationUserId = User.Identity.GetUserId();
                db.Answers.Add(answer);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = answer.QuestionId });
            }

            return View(answer);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Stack Overflow";
    ViewBag.Message = "Stack overflow is a part of Stack Exchange. It is a network of question-and-answer websites on topics in varied fields, each site covering a specific topic, where questions, answers, and users are subject to a reputation award process. The sites are modelled after Stack Overflow, a Q&A site for computer programming questions that was the original site in this network. The reputation system allows the sites to be self-moderating. As of April 2017, the three most popular sites in the network are: Stack Overflow, Super User and Ask Ubuntu. User contributions are licensed under Creative Commons Attribution-ShareAlike 3.0 Unported";
}
<h2>@ViewBag.Title.</h2>
<p>@ViewBag.Message</p>

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h1>@ViewBag.Title</h1>

<address>
    FAMCS BSU <br />
    Minsk, Belarus<br />
</address>

<address>
    <strong>Support:</strong>   <a>StackOverflow@example.com</a>
</address>

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="container">
    <div class="canvas">
        <canvas id="field" width="1100" height="600"></canvas>
    </div>
    <div>
        <input type="button" value="Start" id="start" />
        <input type="button" value="Stop" id="stop" />
        <label class="generation">
            Generation:
        </label>
        <span id="generationNum">0</span>
    </div>
</div>
<div class="jumbotron">
    <h2>Stack Overflow</h2>
    <p class="lead">Stack Overflow is a place where you can exchange your experience in software and web developing. It's a part of the world's most popular platform to ask and to get answers.</p>
    @Html.ActionLink("Ask Question", "Create", "Questions")
</div>

@model IEnumerable<STACK.Models.Question>

@{
    ViewBag.Title = "Stack Overflow";
}

<div class="container">
    @foreach (var item in Model)
    {
        
        <div style="height:200px;" class="col-md-6" id="@Html.DisplayFor(modelItem => item.Id)">
            <hr />
            <h2>@Html.ActionLink((item.Text), "Details", "Questions", new { id = item.Id }, null)</h2>
            <div class="row">
                <div class="col-md-5">Asked by: @Html.DisplayFor(modelItem => item.ApplicationUser.UserName)</div>
                <div calss="col-md-5">Date: @Html.DisplayFor(modelItem => item.Date)</div>  
            </div>
            <strong>Answers: @Html.DisplayFor(modelItem => item.Answers.Count)</strong>
        </div>
        
    }
</div>