UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Models/Answer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace STACK.Models
{
    public class Answer
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public DateTime Date { get; set; }

        public int Rating { get; set; }

        public int QuestionId { get; set; }
        public virtual Question Question { get; set; }

        public string ApplicationUserId { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }
        public Answer()
        {
            Date = DateTime.Now;
        }
    }
}

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Models/Question.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace STACK.Models
{
    public class Question
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public DateTime Date { get; set; }

        public virtual ICollection<Answer> Answers { get; set; }

        public string ApplicationUserId { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }
        public Question()
        {
            Date = DateTime.Now;
        }
    }
}

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using STACK.Models;

namespace STACK.Controllers
{
    public class AnswersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Answers
        public ActionResult Index()
        {
            var answers = db.Answers.Include(a => a.ApplicationUser).Include(a => a.Question);
            return View(answers.ToList());
        }

        // GET: Answers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }
        public ActionResult RatingUp(int ?id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            answer.Rating++;
            db.SaveChanges();
            int questionId = answer.QuestionId; 
            return RedirectToAction("Details", "Questions", new { id = questionId });
        }

        // GET: Answers/Create
        public ActionResult Create()
        {
           // ViewBag.ApplicationUserId = new SelectList(db.ApplicationUsers, "Id", "Email");
            //ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Text");
            return View();
        }

        // POST: Answers/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Text,Date,QuestionId,ApplicationUserId")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Answers.Add(answer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

           // ViewBag.ApplicationUserId = new SelectList(db.ApplicationUsers, "Id", "Email", answer.ApplicationUserId);
           // ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Text", answer.QuestionId);
            return View(answer);
        }

        // GET: Answers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
           // ViewBag.ApplicationUserId = new SelectList(db.ApplicationUsers, "Id", "Email", answer.ApplicationUserId);
            //ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Text", answer.QuestionId);
            return View(answer);
        }

        // POST: Answers/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Text,Date,QuestionId,ApplicationUserId")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           // ViewBag.ApplicationUserId = new SelectList(db.ApplicationUsers, "Id", "Email", answer.ApplicationUserId);
            //ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Text", answer.QuestionId);
            return View(answer);
        }

        // GET: Answers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // POST: Answers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Answer answer = db.Answers.Find(id);
            db.Answers.Remove(answer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using STACK.Models;
using Microsoft.AspNet.Identity;
using STACK.ViewModels;

namespace STACK.Controllers
{
    public class QuestionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Questions
        public ActionResult Index()
        {
            return View(db.Questions.ToList());
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            var qa = new QuestionAnswerViewModel
            {
                Question = question,
                NewAnswer = new Answer()
            };
            qa.NewAnswer.QuestionId = qa.Question.Id;
            return View(qa);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        // POST: Questions/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {

                question.ApplicationUserId = User.Identity.GetUserId();
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = question.Id });
            }

            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Question question = db.Questions.Find(id);
                if (question == null)
                {
                    return HttpNotFound();
                }
                return View(question);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }           
        }

        // POST: Questions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                question.ApplicationUserId = User.Identity.GetUserId();
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {

            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Question question = db.Questions.Find(id);
                if (question == null)
                {
                    return HttpNotFound();
                }
                return View(question);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }            
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        //GET : Questions/Answer/5
        public ActionResult Answer(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                Answer answer = new Answer();
                answer.QuestionId = id;
                return View(answer);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Answer(Answer answer)
        {
            if (ModelState.IsValid)
            {
                answer.ApplicationUserId = User.Identity.GetUserId();
                db.Answers.Add(answer);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = answer.QuestionId });
            }

            return View(answer);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Views/Questions/Answer.cshtml
@model STACK.Models.Answer

@{
    ViewBag.Title = "Answer";
}

<h2>Answer</h2>




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.QuestionId)

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Views/Questions/Create.cshtml
@model STACK.Models.Question

@{
    ViewBag.Title = "Create";
}

<h2>Create question</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>     

        <div class="form-group">
            <div class="col-md-1">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    <strong>@Html.ActionLink("Back to List", "Index")</strong>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Views/Questions/Delete.cshtml
@model STACK.Models.Question

@{
    ViewBag.Title = "Delete";
}

<div>
    <h2>Are you sure you want to delete this question?</h2>
    <hr />
    <h3>@Html.DisplayFor(model => model.Text)</h3>
    <div>
        <strong>@Html.DisplayNameFor(model => model.Date)</strong>:
        @Html.DisplayFor(model => model.Date)
    </div>
    <br/>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" />
        <strong>@Html.ActionLink("Back to List", "Index")</strong>
    </div>
}

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Views/Questions/Details.cshtml
@model STACK.ViewModels.QuestionAnswerViewModel

@{
    ViewBag.Title = "Details of the question";
}


<div class="jumbotron row">
    <div class="col-md-6">
        <h1>@Html.DisplayFor(model => model.Question.Text)</h1>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Question.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Question.Date)
            </dd>

            <dt>
                Asked By
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Question.ApplicationUser.UserName)
            </dd>
        </dl>
    </div>
    <div class="col-md-3 col-md-offset-3">
        <br/>
        @if (User.Identity.IsAuthenticated)
        {
            @Html.ActionLink("Edit Question", "Edit", new { id = Model.Question.Id })<br />;
            @Html.ActionLink("Delete Question", "Delete", new { id = Model.Question.Id })<br />;
        }
        @Html.ActionLink("Back to Questions", "Index")
    </div>
</div>


<h1>Answers to the question</h1>
@foreach (var ans in Model.Question.Answers)
{
    @Html.Partial("_Answer", ans)
}



<div class="col-md-12 row">
    @if (User.Identity.IsAuthenticated)
    {
        <div class="jumbotron col-md-5">
            <h2>Leave your answer</h2>
            @Html.Partial("_AnswerForm", Model.NewAnswer)
        </div>
        <div class="col-md-7">

        </div>
    }
    else
    {
        <p>
            @Html.ActionLink("Back to Questions", "Index")
        </p>
    }
</div>

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Views/Questions/Edit.cshtml
@model STACK.Models.Question

@{
    ViewBag.Title = "Edit";
}

<h2>Edit question</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<strong>
    @Html.ActionLink("Back to List", "Index")
</strong>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Views/Questions/Index.cshtml
@model IEnumerable<STACK.Models.Question>

@{
    ViewBag.Title = "Questions";
}




<table class="table table-striped">
    <tr>
    <th>
        <strong>Questions</strong>
    </th>
    <th>
        Number of Answers:
    </th>
    <th>
        Date:
    </th>
    <th>
        Asked by:
    </th>
    <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink((item.Text), "Details", "Questions", new { id = item.Id }, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Answers.Count)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationUser.UserName)
        </td>
    </tr>
}
</table>

<strong>@Html.ActionLink("Ask a new question", "Create")</strong>
    

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Views/Questions/_Answer.cshtml
@model STACK.Models.Answer

<div class="col-md-12" id="@Model.Id">
    <hr/>
    <h2>@Model.Text</h2>
    <div class="row">
        <div class="col-md-3">
            <strong>Answered by</strong>:
            @if (Model.ApplicationUser != null)
            {
                @Model.ApplicationUser.UserName

            }
            else
            {
                <p>"Unauthorized user"</p>
            }
        </div>
        <div calss="col-md-3"><strong>Date</strong>: @Model.Date</div>
        <div class=" rating">@Html.ActionLink("+", "RatingUp", "Answers", new { id = Model.Id }, null)</div>
        <div class="col-md-1 "><strong>@Model.Rating</strong></div>
    </div>
    <br/>
    <hr />
    <br />
</div>

UP/Task10/StackOverflow/3.0 StackOverflow/STACK/Views/Questions/_AnswerForm.cshtml
@model STACK.Models.Answer

@using (Html.BeginForm("Answer", "Questions", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">

        <div class="form-group">
            @Html.HiddenFor(m => m.QuestionId)
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>
}